title: Lightspeed core service
description: Lightspeed core service
baseurl: "/lightspeed-stack"
url: "https://lightspeed-core.github.io/lightspeed-stack/"

heading_anchors: true
search_enabled: true

aux_links:
  "Github repository":
    - "https://github.com/lightspeed-core/lightspeed-stack/"

footer_content: "Copyright &copy; 2025 Red Hat and external authors"

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - sources.tmpl.md

theme: jekyll-theme-leap-day
