name: Black

on:
  - push
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    env:
      PDM_BUILD_DIR: /tmp/pdm-build
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.11'
      - name: Black check
        run: uv tool run black --check .
